server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
      - id: News
        uri: http://localhost:9091
        predicates:
        - Path=/news/**
      - id: NewzSource
        uri: http://localhost:9090 
        predicates:
        - Path=/newssource/mongo/**
      - id: TokenIssuerApp
        uri: http://localhost:9001
        predicates:
        - Path=/loginpage/**
       